name: RealLightWeightHomes
version: 0.3
author: Kilian Legters
main: me.kilianlegters.RealLightWeightHomes
description: Literally just /(set/del)home.
api-version: 1.14

commands:
  sethome:
    description: Sethome command.
    usage: /<command> <name>
  home:
    description: Home command.
    usage: /<command> <name>
  delhome:
    description: Delhome command.
    usage: /<command> <name>

permissions:
    reallightweighthomes:
        description: RealLightWeightHomes permission.
        default: true